### ISSUE TITLE
Looks nice, but what does it actually do?

### ISSUE THREAD

**Issue by chrishobcroft** [noman-land/ethercam#1]
This repo looks interesting.

But it's kinda hard to understand what it actually does...!

Would help to explain a user journey of using this thing.

PS, will you be in ethb3rlin?

**Comment by noman-land** [comment]
Thanks @chrishobcroft. Good call. This was originally a project from EthBoston in 2019. I've added a link to the README that links out to the original project submission. 

https://devpost.com/software/ethercam

I never did get around to finishing the project which is why the README is so bare. I will one day finish it though. 

Also, yes I will be at EthBerlin!
